### ISSUE TITLE
Figure out a way to handle errors in treasury token queries while listing token balances

### ISSUE THREAD

**Issue by ezekiiel** [DA0-DA0/dao-contracts#117]
Currently we just return a default value of zero if an error occurs during the query. This is good because it means that a misbehaving token won't cause queries to fail entirely but we might want to investigate ways that these errors could be displayed.

**Comment by JakeHartnell** [comment]
@ezekiiel is this still relevant?

**Comment by ezekiiel** [comment]
V1 contracts now error if any of the balance subqueries fail. Think this is a reasonable approach here. Contracts allow listing only the addresses (w/o balances) so there is a pretty straightforward recovery path as well.
