### ISSUE TITLE
Use sub-account for proposal deposit balances

### ISSUE THREAD

**Issue by ben2x4** [DA0-DA0/dao-contracts#12]
The current implementation of proposal deposits has a hidden foot-gun that the dao could create a proposal to spend all of its cw20 balance and accidentally spend the proposal deposit balances. Storing the proposal deposit balances in a sub account using https://github.com/CosmWasm/cw-plus/tree/main/contracts/cw1-whitelist would make this distinction more clear and make it unlikely the dao would accidentally spend proposal deposits. Of course, the DAO could always spend the deposits on purpose but such is the will of the people 🤷‍♂️ .

**Comment by JakeHartnell** [comment]
Might be a better way of creating a sub-account. We should ask around in the CosmWasm Discord.

**Comment by ben2x4** [comment]
Ah interesting, will see what people have to say!

**Comment by JakeHartnell** [comment]
Tests should be written for this. See #47 for context.

**Comment by JakeHartnell** [comment]
Closing as this won't be relevant anymore with the v1 architecture.
