### ISSUE TITLE
Allow only signers or DAO members to execute transactions

### ISSUE THREAD

**Issue by JakeHartnell** [DA0-DA0/dao-contracts#147]
https://twitter.com/poolpitako/status/1487486538825060352?s=20&t=yDwEhQi75PaHN6EHX-8OPw

> can it be so that only contract signers can execute by default, to not get ^^ situations or MEV extraction

Inspired by @ValarDragon. :pray: 

Think this makes a lot of sense... right now anyone can execute a transaction after it's been passed. This can allow for some weird situations. Think a better default would be to have only signers or DAO members be able to execute transactions.

Could make it a setting potentially...

Relevant article: https://blog.gnosis.pm/gnosis-safe-mev-how-to-mitigate-it-347e13535e34

**Comment by verminator23** [comment]
@JakeHartnell Great idea. I can tackle this

**Comment by verminator23** [comment]
@JakeHartnell Is it sufficient to just check if the sender has a staked balance?

**Comment by ezekiiel** [comment]
> Is it sufficient to just check if the sender has a staked balance?

Yup :) or in the case of a multisig you can check if they have voting power.

**Comment by JakeHartnell** [comment]
Closed with: https://github.com/DA0-DA0/dao-contracts/pull/166
