### ISSUE TITLE
Bug Bounty Contracts

### ISSUE THREAD

**Issue by gavindoughtie** [DA0-DA0/dao-contracts#157]
We're so close to being able to do bug bounty contracts (though a regular spend proposal would do in the meantime). It would be neat to have a "github is the oracle" integration so when the bug closes the (approved) contract auto-executes.

**Comment by JakeHartnell** [comment]
Simpler v1 might be just to use the `cw20-escrow` contract...
1. DAO instantiates and funds contracts
2. Some does the work, and makes a proposal to be paid out from the escrow contract
3. DAO approves or rejects

**Comment by elsehow** [comment]
Once we have the DAO DAO treasury set up, perhaps we could create a bounty to create this bounty program.

**Comment by Callum-A** [comment]
Does the cw20-escrow support creating a bounty without a recipient? Or would we only create said bounty escrow once an issue has been assigned and we have the recipient.

May need to expand cw20-escrow's functionality a little.

**Comment by Callum-A** [comment]
This is functionality is added under cw-tokens, pending merge of this [PR](https://github.com/CosmWasm/cw-tokens/pull/9).

**Comment by JakeHartnell** [comment]
Great, when that's merged, let's test this out with Genesis DAO and make sure it gets documented.

**Comment by Callum-A** [comment]
My PR on cw-tokens is now merged we can now move forward with this

**Comment by JakeHartnell** [comment]
> My PR on cw-tokens is now merged we can now move forward with this

Closing here as this can be handled in a separate repo.
