### ISSUE TITLE
Dissolving a DAO

### ISSUE THREAD

**Issue by elsehow** [DA0-DA0/dao-contracts#158]
Some users understandably want to "dissolve" or "delete" a DAO.

Making 'deletion' work in practice will involve both the UI and the contracts. But, we may want to consider what we want that to look like from the contract perspective.

I'm imagining a governance proposal with a message that changes
- the title to "DEPRECATED - IGNORE"
- the description to the same
- maybe some other stuff?

What do folks think?

**Comment by JakeHartnell** [comment]
Think the main issue is dissolving the treasury... like if there is money in the DAO it should be distributed to all the stakers...

**Comment by elsehow** [comment]
A really simple way around this is to simply burn the treasury. Then we display a huge warning to the users that the treasury will be burned if the proposal passes. It will be up to the DAO to manage that process in a separate proposal.

**Comment by JakeHartnell** [comment]
> A really simple way around this is to simply burn the treasury. Then we display a huge warning to the users that the treasury will be burned if the proposal passes. It will be up to the DAO to manage that process in a separate proposal.

That's fine for the DAO governance token... but what if the DAO is holding other assets?

**Comment by elsehow** [comment]
I mean, it would be bad if people burned a treasury that had $JUNO in it, but isn't it kind of up to them to do that if they want to? Our responsibility is to make sure they understand that this is what will happen if the "delete DAO" proposal passes.

**Comment by verminator23** [comment]
@elsehow Hmm... burning the treasury doesn't seem right if the DAO is holding other assets outside of the DAO token. I agree with @JakeHartnell that it makes sense to distribute the treasury to stakeholders.

**Comment by verminator23** [comment]
@elsehow I get it. But why would a DAO need to do that? In most cases, those funds would be allocated elsewhere

**Comment by elsehow** [comment]
@verminator23 OK, I am convinced. I suppose distributing the treasury is just a spend proposal with some defaults (distribute by governance weight) - so easy enough.

**Comment by JakeHartnell** [comment]
Closing in favor of #266
