### ISSUE TITLE
Adding "titles" or "permissions"

### ISSUE THREAD

**Issue by elsehow** [DA0-DA0/dao-contracts#159]
Some users want special roles or permissions.

DAOs could mint a sort of "permission token" that grants the bearer scoped permissions within some application logic. It could be worth thinking about how to support this with our existing contracts.

**Comment by elsehow** [comment]
Perhaps related to #131 - permission tokens could be NFTs.

**Comment by verminator23** [comment]
Does it need to be tied to a token? This reminds me of OpenZeppelin roles https://docs.openzeppelin.com/contracts/4.x/api/access which isn't token based. Would be simpler to implement and reason about. There would just a table for permissions / roles, and you'd have modifiers that would check that the caller has an associated permission

**Comment by verminator23** [comment]
EOSIO custom permission is the best implementation I've seen of this https://developers.eos.io/welcome/v2.1/smart-contract-guides/linking-custom-permission IMO

**Comment by elsehow** [comment]
Definitely doesn't need to be tied to a token! I like this better.

**Comment by JakeHartnell** [comment]
The Authz module could be used for this: https://docs.cosmos.network/v0.44/modules/authz/01_concepts.html#Authorization

> x/authz module defines interfaces and messages grant authorizations to perform actions on behalf of one account to other accounts.

**Comment by JakeHartnell** [comment]
This is being done with the Authorizations module as well as SBTs.

See:
- #358
- #311

Closing in favor of those issues.
