### ISSUE TITLE
Private (ZK?) voting with receipt-freeness

### ISSUE THREAD

**Issue by JakeHartnell** [DA0-DA0/dao-contracts#184]
Private voting with zero-knowledge proofs will be an essential feature for some communities.

There are quite a few ZK Rust libraries, I'm not sure which might be best to use... so we should start exploring.

We'll implement as a plugable governance module after we refactor the main DAO contracts.

**Comment by verminator23** [comment]
This is awesome. I've been working with a guy on implementing a cosmwasm mixer for Juno. We've made a bit of progress with getting zk proof verification done in a cosmwasm, but still a lot more to do. Would love to chat further about this.

**Comment by albttx** [comment]
Hey ! i could give a hand on this :) 
ping me once you're done refactoring

Here some useful libraries:

- https://github.com/iden3/circom + https://github.com/gakonst/ark-circom

I'll keep updating this ticket for libraries / ideas :)

**Comment by JakeHartnell** [comment]
Thanks @albttx!

**Comment by elsehow** [comment]
Changing the issue name to reflect our current best understanding of the problem.

**Comment by JakeHartnell** [comment]
Closing as this work will come with v3.

**Comment by fluffydonkey** [comment]
@vernonjohnson I would love to get in touch about cosmwasm zk's!
