### ISSUE TITLE
Improve error for no voting power at height

### ISSUE THREAD

**Issue by Callum-A** [DA0-DA0/dao-contracts#185]
Taking a look into the DAO contract.

We only return a Unauthorized error when a user has no voting power at the start height of a proposal. This could easily be improved with a NoVotingPowerAtHeight error which takes height as a parameter.

The current code for the unauthorized error is located here: https://github.com/DA0-DA0/dao-contracts/blob/main/contracts/cw3-dao/src/contract.rs#L290

**Comment by JakeHartnell** [comment]
Believe this is done.
