### ISSUE TITLE
Rejected proposals may not be refunded.

### ISSUE THREAD

**Issue by ezekiiel** [DA0-DA0/dao-contracts#191]
Proposals are marked as rejected if a vote comes in that would cause the proposal to get sufficient no votes to pass the proposal:

https://github.com/DA0-DA0/dao-contracts/blob/8674d01516dbc80feab5515215225acbde5744b5/contracts/cw3-dao/src/contract.rs#L308

In order to receive a refund for a failed proposal the proposal must be closed via the `execute_close` method. This method will not execute if the proposal is rejected:

https://github.com/DA0-DA0/dao-contracts/blob/8674d01516dbc80feab5515215225acbde5744b5/contracts/cw3-dao/src/contract.rs#L383-L389

This means proposals that expire they can be closed for a proposal refund, but for proposals that are rejected may not. We have a test for the expired case but not for the rejected case:

https://github.com/DA0-DA0/dao-contracts/blob/8674d01516dbc80feab5515215225acbde5744b5/contracts/cw3-dao/src/tests.rs#L1554-L1555

We should either change this behavior or change the config option to `refund_expired_proposals`.

**Comment by JakeHartnell** [comment]
@ezekiiel can we close this one?

**Comment by ezekiiel** [comment]
Yep! One of the many little bugs that go away in V1. :)
