### ISSUE TITLE
Add a voting power module based on staked token balances.

### ISSUE THREAD

**Issue by ezekiiel** [DA0-DA0/dao-contracts#194]
The last contract to start for the v1 contracts is a voting power module based on staked token balance. An example voting power module can be found [here](https://github.com/DA0-DA0/dao-contracts/tree/zeke/contracts-v1/contracts/cw20-balance-voting) which demonstrates implementing the voting power interface.

I believe that this contract can be separated from the current staking contract and register itself as a hook receiver to handle balance updates. Would be nice to support vote delegation here as well but I think we can do that as a follow up issue.

**Comment by Callum-A** [comment]
Going to take a look at this, assigning to myself for now.

**Comment by Callum-A** [comment]
Closed with #199
