### ISSUE TITLE
Implement voting power module which uses cw4-groups.

### ISSUE THREAD

**Issue by ezekiiel** [DA0-DA0/dao-contracts#196]
This will be needed to support multisigs in the v1 contracts. This will implement the voting module interface. Like the staking voting module this should likely take advantage of hooks available from the existing cw-plus cw4-groups contract.

**Comment by orkunkl** [comment]
Wdym by a module? It would be great to have some links to the context if there is any.

**Comment by orkunkl** [comment]
Found it here https://docs.google.com/document/d/1OjUZAl8ty6jZ59ryEyUUuifzectb3RigUSa8RLm4GsY/edit#heading=h.nf08vukjipch

**Comment by ezekiiel** [comment]
Some additional context as well because that doc is a little high level.

Voting power modules need to implement three queries:

1. `VotingPowerAtHeight { address:  String, height: Option<u64> }`.
2. `TotalPowerAtHeight { height: Option<u64> }`
3. `Info {}`

These queries can be derived on an enum with the `voting_query` macro [here](https://github.com/DA0-DA0/dao-contracts/blob/d7c103c51eb4f03f9d73c3e765e39c39b1a279f1/contracts/cw-governance-macros/src/lib.rs#L50). Those queries are then expected to return data in the shapes defined [here](https://github.com/DA0-DA0/dao-contracts/blob/d7c103c51eb4f03f9d73c3e765e39c39b1a279f1/contracts/cw-governance-interface/src/voting.rs).

**Comment by ezekiiel** [comment]
@orkunkl  an example contract is [here](https://github.com/DA0-DA0/dao-contracts/tree/d7c103c51eb4f03f9d73c3e765e39c39b1a279f1/contracts/cw20-balance-voting). This one implements voting power queries based on the current cw20 balance of the user.

Happy to chat this week if you'd like to walk through this / give some feedback.

**Comment by Callum-A** [comment]
Closed with #205
