### ISSUE TITLE
Allow passing proposals on plurality votes if passing threshold is not met by the deadline

### ISSUE THREAD

**Issue by NoahSaso** [DA0-DA0/dao-contracts#203]
Currently, the passing threshold is a hard requirement for any proposals to go through. This behavior may halt DAOs whose members are inconsistently active.

We should add the option to pass proposals / select the winning choice based on plurality at the end of the voting period, with the passing threshold serving as an early approval if met.

This is similar to how voting works in governments.

**Comment by Callum-A** [comment]
I like this, I think this should be a part of v1 however, as we can have differing governance modules or even just a flag on the main one? Some people may like this voting system but others may want to encorporate another. Thoughts?

**Comment by NoahSaso** [comment]
> I like this, I think this should be a part of v1 however, as we can have differing governance modules or even just a flag on the main one? Some people may like this voting system but others may want to encorporate another. Thoughts?

Yes! @ezekiiel and I talked a bit about this and realized plurality voting is actually just a special case of the threshold/quorum voting module where quorum = 0. So this is actually already built in :) and his quorum frontend changes will enable this functionality right away!

**Comment by NoahSaso** [comment]
Since threshold+quorum is a passing option on the UI, the UI will be able to set the fields accordingly based on the selected voting module, so no contract changes are necessary!
