### ISSUE TITLE
Allow voters to change their vote

### ISSUE THREAD

**Issue by NoahSaso** [DA0-DA0/dao-contracts#204]
Revoting on proposals before they pass may be functionality we want to allow DAOs to enable/disable. Let's think about this a bit.

I haven't heard much user feedback requesting this, and I think intuitively people expect votes to be final. Though it would be a nice option to have, especially when there's money involved and mistakes are possible.

**Comment by Callum-A** [comment]
I think we should add this to v1 as a flag on the appropriate modules? Thoughts?

**Comment by NoahSaso** [comment]
> I think we should add this to v1 as a flag on the appropriate modules? Thoughts?

Agreed, think it would be a nice addition to v1 and not too much additional work. @ezekiiel ?

**Comment by ezekiiel** [comment]
The challenge with this is that if we allow revoting we can't close proposals before they have timed out. Ex: everyone votes yes and then changes their minds => can't close after the everyone votes yes. IMO this might be best as a separate proposal module.

**Comment by elsehow** [comment]
Related/possibly merge? #285

**Comment by elsehow** [comment]
> The challenge with this is that if we allow revoting we can't close proposals before they have timed out. Ex: everyone votes yes and then changes their minds => can't close after the everyone votes yes. IMO this might be best as a separate proposal module.

@ezekiiel I think this is right. Perhaps you and @janitachalam can keep this spec in mind as you go through #279 ? I do think we want the ability to change votes for v1, so it would be good to figure out how best to do this on the new governance modules coming down the pipeline.
