### ISSUE TITLE
Support hooks in v1 staked balance voting contract

### ISSUE THREAD

**Issue by Callum-A** [DA0-DA0/dao-contracts#207]
Once hooks are implemented and merged we should add them to our v1 staked balance voting contract module so we do not have to query the staking contract directly.

**Comment by Callum-A** [comment]
Hooks are now in, so this is actionable. Look at cw4-voting for an example of how you might use this for staking

**Comment by Callum-A** [comment]
On hold for now, we can cache data sent to us by hooks, however there is a chance if an existing staking contract is used this cache may not contain data, e.g. for heights prior to the instantiation of the voting contract.

**Comment by JakeHartnell** [comment]
> Once hooks are implemented and merged we should add them to our v1 staked balance voting contract module so we do not have to query the staking contract directly.

@Callum-A, what's the status of this. Can we close this?

**Comment by Callum-A** [comment]
This can be closed
