### ISSUE TITLE
Support DAO initial balance in staked balance voting module.

### ISSUE THREAD

**Issue by ezekiiel** [DA0-DA0/dao-contracts#208]
The old contracts support allocating a token amount to the DAO on instantiation. We should support this in the `TokenInfo::New` variant.

**Comment by Callum-A** [comment]
Great catch, easily missed

**Comment by ezekiiel** [comment]
Just noticing this stuff going through the frontend. :) Likely more little things to come. Also completely missed this when writing the contract.
