### ISSUE TITLE
V1 contracts design

### ISSUE THREAD

**Issue by ezekiiel** [DA0-DA0/dao-contracts#225]
# DAO DAO Contracts Design

_Note: the naming of modules here is a WIP. Would love feedback._

The DAO DAO v1 contracts are designed to be modular and pluggable. The
vision is that with sufficiently modular contracts any portion can be
swapped out at will in response to a security vulnerability, bug, or
upgrade.

At a high level, the contracts consist of four parts:

1. A router contract which manages addition and removal of modules,
   execution of messages, and holding of native tokens.
2. A core contract which handles determining the voting power and
   membership status of addresses.
3. Any number of controller contracts which handle voting and
   proposals.
4. Any number of item contracts which may be associated with the
   router contract. These handle things like non-native token
   ownership, groups, and whatever other state / logic we'd like to
   associate with governance down the line.

Here's a high level diagram of how those all fit together:

```
                                                +--------------+
                                                |              |
                                              /-+  controller  |
   +------------+       +-------------+  /----  |              |
   |            |       |             +--       +--------------+
   |  core      +-------+  router     |
   |            |       |             +--       +--------------+
   |            |       |             |  \----  |              |
   +------------+       +---/---------+       \-+ controller   |
                           /                    |              |
                          /                     +--------------+
                         /
                   +----/------+
                   |           |
                   |  item     |
                   |           |
                   +-----------+
```

## The router contract

```
     (2) validate is registered controller
     +-----------------+
     |                 |
     |                 |  (1) execute message hook
     |    router       | <------------
     |                 |
     |                 |
     +-----------------+
             |
             | (3) execute the message
             v
```

The router contract executes messages on behalf of the controller
modules. To do this it has an `ExecuteProposalHook { msgs }`
method. This method may only be called by controller modules that have
been registered with the governance contract. Controller modules may
call this method when they have messages they would like to see
executed. For example, this may occur when a controller module has
passed a proposal.

The router contract may also route queries between controller modules
and its core module about the voting power. To this end it implements
the same interface for queries that the core modules must implement.
Specifically, it implements a `VotingPowerAtHeight { addr, height }`
and `TotalPowerAtHeight { height }` query. These queries will be
proxied to the governance module's core module and that response
returned.

At all times the router contract must have one core module associated
with it and at least one controller module associated with it.

The router contract may add and remove these modules at will by
calling the `UpdateVotingModule` and `UpdateGovernanceModules` methods
on itself. In practice this occurs by controller modules sending a
execute hook that will cause the router contract to call that method
on itself.

## Items

```
   +---------------+                  +----------------+
   | router        |                  |                |
   |               |                  |special purpose |
   |               |              /-->|contract        |
   |           +-----+    /-------    |                |
   |           | key |----            +----------------+
   +-----------+-----+
```

Items are key value pairs stored in the router contract. Their key is
a string and their value is an address of a contract that key refers
to. For example, for a governance contract that has a notion of groups
of users (ex. Alice belongs to the core team) might have a key which
is `"groups"` with a value being an address of a contract that manages
these groups.

The router contract may add and remove these items by calling the
`SetItem` and `RemoveItem` methods on itself. In practice this occurs
by controller modules sending a execute hook that will cause the
router contract to call that method on itself.

## The core contract

```
      +------------------+
      |                  |
      |                  |   voting power queries
      |                  | <------------
      |   core           |
      |   (voting power  |
      |    management)   |
      |                  |
      |                  |
      +------------------+
```

The core contract manages the voting power of governance members. For
example, for a multisig style voting system this contract may allow
the DAO to add and remove members and manage that member list. For a
staking style voting system this module may allow addresses to stake
tokens and report information about the number of tokens that they
have staked.

Core contracts must implement a `VotingPowerAtHeight` and
`TotalPowerAtHeight` query which controller modules will use to
determine the weight of an addresses vote on a proposal. For core
modules that do voting based on a token they must also implement a
`TokenContract` query which will return the address of the token being
used. Controller modules that support proposal deposits may query this
information to determine what token to accept for deposits.

In practice, there are no hard requirements on what queries that a
core module actually implements as sufficiently custom governance
modules may query the module directly and may only be compatible with
specific voting systems.

## Controller contracts

```
 +----------------+                    +--------------+
 | router         |   execution hooks  | controller   |
 |                | <------------------|              |
 |                |                    |              |
 |                |                    |              |
 +----------------+                    +--------------+
                                               ^
                                               | proposal information
                                               |
```

Controller contracts are extremely flexible and don't have any
particular interface they must implement. They only need to be aware
of how to execute the proposal hook on the router contract.

It is imagined that controller contracts will mostly implement some
kind of proposal and voting system. For example, they might support
ranked choice voting, multiple choice voting, or quadratic voting. In
practice, this is not enforced and a router contract may register any
controller contract it would like.

## Frontend integration

```
                   (2) what kind of module are you?
   +-------------+ -----------------> +----------+
   | frontend    |                    | module   |
   |             |                    |          |
   |             | -----------------> +----------+
   +-------------+ (3) module specific queries
          |
          |
          | (1) what modules do you have?
          |
          v
    +-----------+
    |router     |
    |           |
    |           |
    +-----------+
```

All modules in this system must implement an `Info {}` query which
return the contract's name and its version. To render a module the
frontend will then query a the router contract for its modules and
then query those modules for their info.

**Comment by NoahSaso** [comment]
I think this should be moved to a wiki or discussion. A wiki would make it more collaborative, and this seems like a design we want documented in some way and not get closed in the future 🙂

**Comment by ezekiiel** [comment]
Closing this as I think we have settled on a nice naming system. Have moved this design spec into a wiki page: https://github.com/DA0-DA0/dao-contracts/wiki/DAO-DAO-v1-Contracts-Design
