### ISSUE TITLE
Support DAO visual customization.

### ISSUE THREAD

**Issue by ezekiiel** [DA0-DA0/dao-contracts#229]
One thing we'd really like to support is the ability for a DAO to style its homepage via proposals. For now I'd imagine this mostly applies to the accent color the page uses, but we could expand this to other things down the line.

In order to do this we'll need a contract to support this customization. I'd imagine that this contract mostly just stores a JSON blob that has the DAO's customization choices. The DAO can then modify those choices. There is still design work to be done here. :)

**Comment by JakeHartnell** [comment]
Starting to wonder if we should just do DAO metadata with an IPFS URI...

**Comment by ezekiiel** [comment]
https://github.com/DA0-DA0/dao-contracts/issues/234 is probably the better approach here.

**Comment by JakeHartnell** [comment]
Closing in favor of #234
