### ISSUE TITLE
DAO registry contract.

### ISSUE THREAD

**Issue by ezekiiel** [DA0-DA0/dao-contracts#230]
This contract will be managed by a DAO or Multisig. It will support the following:

1. Registering a contract.
2. Listing all of the contracts that have been registered.
3. Verifying a contract (the managing address will be responsible for this).
4. Taking a payment to register a contract.
5. Modifying the payment required to register a contract (managing address responsible).

We'll use this in the UI to prevent spam / testing DAOs from cluttering list results. DAOs will need to pay in order to have their DAO listed in on the DAO list and (once the indexer is running) to appear in search results.

The managing DAO will also be able to "verify" a contract which will place a check next to the DAO in the UI. For example, one could verify the Marble DAO and then visitors could be sure they are not visiting a fake one.

**Comment by JakeHartnell** [comment]
Talking with @Callum-A about this. We could use (de)NS subpaths: https://dens.sh/

Then whatever the registry DAO is would have admin rights over the namespace.

**Comment by Callum-A** [comment]
I have a contract which allows permisionless minting of subpaths on a given name, could be a potential use case for the DAO token! https://github.com/Callum-A/whoami-paths

**Comment by JakeHartnell** [comment]
Le done.
