### ISSUE TITLE
Concered about balance voting

### ISSUE THREAD

**Issue by ben2x4** [DA0-DA0/dao-contracts#236]
@ezekiiel thinks this doesn't work as someone could vote, send to another address, and vote again :( 

https://github.com/DA0-DA0/dao-contracts/blob/0ef38f37ac5fcd5768f353612ce4084ba0d3cb69/contracts/cw20-balance-voting/src/contract.rs#L107

**Comment by ezekiiel** [comment]
Yeah. Wrote this as a test contract. Need to add a giant warning lol.

**Comment by JakeHartnell** [comment]
> Yeah. Wrote this as a test contract. Need to add a giant warning lol.

Should probably just delete at some point, but giant warning is fine for now IMO.

**Comment by JakeHartnell** [comment]
Moved to debug folder.
