### ISSUE TITLE
shuffle voting

### ISSUE THREAD

**Issue by janitachalam** [DA0-DA0/dao-contracts#244]
Randomly distribute voting weights over time.

**Comment by Samangan** [comment]
Interested in hearing more about this.

Do we have any smart contracts that use randomness? We would have to use an oracle [like this](https://github.com/confio/rand) right? Which looks like this could greatly increase the gas / byte footprint of our contracts, but maybe it's worth it?

**Comment by JakeHartnell** [comment]
Closing for now. Need a good use-case for this. Feel free to re-open if someone feels there is a strong user story for this.
