### ISSUE TITLE
Rework Root Repo README

### ISSUE THREAD

**Issue by Callum-A** [DA0-DA0/dao-contracts#250]
With the new overhaul the root README has fallen out of date, we need to fix that!

**Comment by ezekiiel** [comment]
Yes!

**Comment by JakeHartnell** [comment]
Each contract should also have a README. Main README should have a list of the contracts and a brief descriptions

**Comment by Callum-A** [comment]
> Each contract should also have a README. Main README should have a list of the contracts and a brief descriptions

Lets open up a branch for this, and have people branch off of that and merge into it for writing READMEs on each contract they feel confident. Allows us to move faster imo

**Comment by JakeHartnell** [comment]
> > Each contract should also have a README. Main README should have a list of the contracts and a brief descriptions
> 
> Lets open up a branch for this, and have people branch off of that and merge into it for writing READMEs on each contract they feel confident. Allows us to move faster imo

Perfect. @ebaker, you mentioned you had some folks interested in technical writing. This would be a great thing to contribute to.

**Comment by Callum-A** [comment]
Created branch `readmes` for this https://github.com/DA0-DA0/dao-contracts/tree/readmes

**Comment by ezekiiel** [comment]
@Callum-A now that we've merged the readmes changes shall we close this?
