### ISSUE TITLE
Finalize V1 Contract Names

### ISSUE THREAD

**Issue by JakeHartnell** [DA0-DA0/dao-contracts#255]
`cw-core` is not very clear. `cw-dao-core` is a little bit better. However this isn't the only contract that needs thought with regards to the name... voting and proposal contracts also need a naming convention! 

Ideally we want a standardized way of naming contracts to make it easier to find contracts via search. Maybe we should follow the `cw#` pattern? Open to ideas.

**Comment by Callum-A** [comment]
+1 stake-cw20 also needs renaming to fit the `cw#` pattern

**Comment by JakeHartnell** [comment]
Would really like to get this finalized for the next release. :joy: 

Naming things is hard.

**Comment by Callum-A** [comment]
I think it's time for more discussion on this, we've renamed the staking contracts to be prefixed with `cw20`, do we just need to pick arbitrary numbers or stick with textual names

**Comment by ezekiiel** [comment]
Closing in favor of #416 .
