### ISSUE TITLE
Implement a DAO liquidation contract.

### ISSUE THREAD

**Issue by 0xekez** [DA0-DA0/dao-contracts#266]
How does a DAO die? Likely by liquidating it's treasury to governance participants.

This liquidation contract should accept a voting module contract, a height, and some funds (cw20, cw721, or native). It should then disperse these assets to members of the voting contract according to their staked proportion.

For example, if a DAO with 100 Juno and 100 members each with equal voting power would like to die it may send its treasury to the liquidation contract. All members at the time of liquidation would then be able to claim 1 Juno.

**Comment by elsehow** [comment]
Bumping this again. Dissolving a DAO is important!
