### ISSUE TITLE
WIP: reference modules deterministically for core <> module interplay

### ISSUE THREAD

**Issue by bmorphism** [DA0-DA0/dao-contracts#275]
![safe_math](https://user-images.githubusercontent.com/1236584/165604912-cb7afc33-6882-493a-8c89-32132525eab2.png)

also, is safe math _really_ safe?! stay tuned for more!

@elsehow @ezekiiel @janitachalam

**Comment by JakeHartnell** [comment]
@bmorphism can you add a bit more context here? We've been tuned in for a while. : )

**Comment by bmorphism** [comment]
I believe I've added this as a placeholder for an issue referenced by @ezekiiel several iterations ago and called out during the Wednesday sessions, need to confirm if still legitimate

**Comment by JakeHartnell** [comment]
Seems to be resolved. Feel free to re-open if not.
