### ISSUE TITLE
Improve Testing Experience

### ISSUE THREAD

**Issue by Callum-A** [DA0-DA0/dao-contracts#296]
It's coming to the time when testing needs to be focused on as this project grows, here are some ideas I have so far:

- Place tests under a subdir and separate by file on components e.g. `src/tests/absolute_count.rs`, `src/tests/percentage.rs`
- Move common test code to a package e.g. moving all `ContractWrapper` calls into a package (so we don't have to implement CW20 wrapper in every contract lol)
- Common voting module setup should also be extracted to a package as I see us using this often
- Enhanced test suite, would be nice (maybe not possible) to give a test a proposal module and the instantiate info and have it run a set amount of tests against it

**Comment by Callum-A** [comment]
Not expecting all of this to be done as one, more something to aim towards

**Comment by Callum-A** [comment]
@janitachalam has started on this in her multiple choice proposal contract, we just need to use these utils where appropriate in other contracts

**Comment by JakeHartnell** [comment]
@0xekez has been implementing a lot of this in his v2 refactor. Think much of this has been implemented, so closing or this issue will be around forever. Feel free to reopen as smaller scoped tickets.
