### ISSUE TITLE
Document proposal hooks behavior.

### ISSUE THREAD

**Issue by 0xekez** [DA0-DA0/dao-contracts#299]
https://github.com/DA0-DA0/dao-contracts/pull/295 discusses an edge case in proposal hooks logic. The current behavior seems correct for the moment, but we should take care to call this out in any documentation we write. These docs should likely be written alongside an implementation of a proposal hooks contract (for example, incentivised voting).

**Comment by Callum-A** [comment]
Have started the effort here, not quite where I want it. Will pick it back up after I'm back from my holiday. https://github.com/DA0-DA0/dao-contracts/wiki/Proposal-Hooks-Interactions

**Comment by JakeHartnell** [comment]
@0xekez is this still relevant?

**Comment by JakeHartnell** [comment]
Feel this has been documented.
