### ISSUE TITLE
Implement "Soul Bound" NFT Contract

### ISSUE THREAD

**Issue by JakeHartnell** [DA0-DA0/dao-contracts#311]
Vitalik has been talking a lot about using non-transferable NFTs: https://vitalik.ca/general/2022/01/26/soulbound.html

Funny enough, I did a thought experiment a while back on how one would build a C-Corp with the DAO DAO V1 contracts, and mentioned a "Title" NFT Contract that was non-transferable except by an admin (usually the DAO). Context: https://gist.github.com/JakeHartnell/8cce816fb7d6e5977f785ca26a26c09a

To do:
- Implement `cw721-non-transferable` by allowing for an optional admin and blocking all messages from executing unless there is an admin
- Create a voting power module for non-transferable NFTs (mvp: simple query NFT balance) 
- Maybe submit upstream to the `cw-nfts` repo: https://github.com/CosmWasm/cw-nfts

**Comment by bmorphism** [comment]
👻

**Comment by JakeHartnell** [comment]
Should be done in `cw-nfts` or one the Stargaze repos. Closing...
