### ISSUE TITLE
7. execute_pause does not enforce maximum pause duration

### ISSUE THREAD

**Issue by janitachalam** [DA0-DA0/dao-contracts#329]
[2022-06-06_Audit_Report_-_DAO_DAO_v0.1.pdf](https://github.com/DA0-DA0/dao-contracts/files/8848873/2022-06-06_Audit_Report_-_DAO_DAO_v0.1.pdf)

Check issue 7 of the attached audit.

**Comment by ezekiiel** [comment]
Pushing back a little against the recommendation: allowing really long pause durations means that one can retire a DAO by pausing it indefinitely. This is a desirable feature when it comes to things like migration to a new core contract.
