### ISSUE TITLE
8. Proposal containing too many messages will cause an out of gas error

### ISSUE THREAD

**Issue by janitachalam** [DA0-DA0/dao-contracts#330]
[2022-06-06_Audit_Report_-_DAO_DAO_v0.1.pdf](https://github.com/DA0-DA0/dao-contracts/files/8848873/2022-06-06_Audit_Report_-_DAO_DAO_v0.1.pdf)

Check issue 8 of the attached audit.

**Comment by ezekiiel** [comment]
I'm inclined to mark this as do-not-fix. We could develop some heuristic around the number of messages that are normally executable, but it is doomed to be problematic as any of those messages could do something with a smart contract entirely out of our control.
