### ISSUE TITLE
12. Contracts should implement a two-step ownership transfer

### ISSUE THREAD

**Issue by janitachalam** [DA0-DA0/dao-contracts#340]
[2022-06-06_Audit_Report_-_DAO_DAO_v0.1.pdf](https://github.com/DA0-DA0/dao-contracts/files/8848907/2022-06-06_Audit_Report_-_DAO_DAO_v0.1.pdf)

Check issue 12 of the attached audit. Evaluate the recommendation for design change.

**Comment by ezekiiel** [comment]
Pushing back a little against the recommendation: allowing really long pause durations means that one can retire a DAO by pausing it indefinitely. This is a desirable feature when it comes to things like migration to a new core contract.
