### ISSUE TITLE
support timestamps in proposals

### ISSUE THREAD

**Issue by janitachalam** [DA0-DA0/dao-contracts#343]
Persist and surface the timestamp of transactions in a proposal (e.g. when it was created, passed, executed) will require some UI work as well

**Comment by Callum-A** [comment]
do we want a `created` field and a `last_updated` field.

Created is set on creation and is never changed.
Last updated is on each proposal state transition open -> pass -> executed etc.

**Comment by janitachalam** [comment]
yes, this is a good way!

**Comment by JakeHartnell** [comment]
What's the status on this?

**Comment by janitachalam** [comment]
Still needs to be addressed. Will get time for it this coming week
