### ISSUE TITLE
Write factory contract that can instantiate a contract with the contract as its own admin.

### ISSUE THREAD

**Issue by ezekiiel** [DA0-DA0/dao-contracts#359]
This contract should likely just take a `Binary` message and a code ID and:

1. Instantiate an instance of the contract with itself as the admin.
2. Do a `WasmMsg::UpdateAdmin` to make the contract its own admin.

**Comment by janitachalam** [comment]
context: this is necessary to allow the core contract to migrate itself, since only the wasm admin can migrate a contract
