### ISSUE TITLE
Write cw20 <-> native token escrow contract.

### ISSUE THREAD

**Issue by ezekiiel** [DA0-DA0/dao-contracts#365]
This contract should be single use and instantiated with an amount of cw20 / native tokens to be exchanged between two counterparties. The two counterparties should then deposit those tokens into the contract. Upon both sides depositing the required amounts the tokens should then be sent through. At any time, if one counterparty has deposited tokens but the other has not they should be able to withdraw their tokens.

**Comment by elsehow** [comment]
I'd expect an escrow contract to be more concerned with time. For example, say Alice and Bob have an escrow contract that swaps 500 $ALICE for 200 $BOB. Alice puts in 500 $ALICE. The contract might stipulate that, if Bob doesn't send the 200 $BOB before XXXX blocks, the contract will then allow Alice (and only Alice) to withdraw her $ALICE at any time

The idea here is that, when you place something in escrow, it should be locked in escrow until the counterparty falls through.

**Comment by ben2x4** [comment]
I think the easiest method here is any counter party can withdraw their funds at any time.

**Comment by elsehow** [comment]
I mentioned this to @ezekiiel in the Discord, but I am now convinced that it is.
