### ISSUE TITLE
Fix Mislabeled Code ID in v1.0.0 Release 🐾 ❤

### ISSUE THREAD

**Issue by siriustaikun** [DA0-DA0/dao-contracts#374]
### Background 
Discovered during audit of [_Juno Proposal 27: Launch Hack Juno SubDAO_](https://www.mintscan.io/juno/proposals/27) by Pupmøs. 

### Overview
[DAODAO Release v1.0.0](https://github.com/DA0-DA0/dao-contracts/releases/tag/v1.0.0) Notes describe the following code IDs:
```
cw20_base: 434
cw4_group: 435
```

In reality, code id 434 represents `crates.io:cw4-group`: https://www.mintscan.io/juno/wasm/code/434

And presumably, `cw20_base` is likely meant to be code id 435, though I have yet to confirm this. 

The proposal, thankfully, is still sound. The base64 decoded submessage for prop 27 describes the correct code ID. 

```
{
    "cw4_group_code_id": 434,
    ...
}
```

**Comment by pyramation** [comment]
@siriustaikun 🐾 🙌🏻

**Comment by ezekiiel** [comment]
Hey! Thanks for making the issue. You're right that these were swapped. I've updated the release notes. :)

You can verify this as well by running:

```
git clone https://github.com/CosmWasm/cw-plus.git
cd cw-plus
docker run --rm -v "$(pwd)":/code \
  --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target \
  --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
  cosmwasm/workspace-optimizer:0.12.6
```

Then downloading the wasm for the code IDs:

```
junod query wasm code 434 434.wasm
junod query wasm code 435 435.wasm
```

And then checking that `shasum 434.wasm` is the same as `shasum artifacts/cw4_group.wasm` to check the cw4-groups contract, then checking that `shasum 435.wasm` is the same as `shasum artifacts/cw20_base.wasm` for the cw20-base contract.
