### ISSUE TITLE
Official or Standarized Query for Listing All Related Dao Contracts for a DAO

### ISSUE THREAD

**Issue by rakataprime** [DA0-DA0/dao-contracts#376]
Currently, it is difficult to get query all of the related contracts for a DAO other than the core, cw20, voting module, and governance modules for DAO explorer tools or certain Dapp integrations like dao governance token gating / authentication. 

I think it may make sense to add  a standardized query or contract state for storing all custom contract module addresses and possible a query standard for staked or all token balances of dao members.

Motivation:
The practical example that motivated this was trying to build a token gating example with staked tokens where it wasn't possible to go from core dao contract address to cw20 staking contract address to staked cw20 token balance of a user which is then added to the cw20 token balance to get total token balance for token gating applications.  

Alternatives:
If there was validator with a full historical block history rpc available than a Dapp could use just query the instantiate message to reference a lot of the related contracts.  However, this would not necessarily be able to reference any module updates correctly. 

Version:
This is in reference to the v1 or later contracts

**Comment by ezekiiel** [comment]
Thanks for the issue. I agree that this is one of the harder parts of the v1 contracts. 

I do think it is possible (though we should add some docs) to do what you want here:

1. Query cw-core for `VotingModule {}`.
2. Query voting module for `StakingContract {}` -> gives you address of the staking contract where you can ask for staked balances.
3. Query voting module for `TokenContract{}` -> gives you address of token contract where you can ask for regular balances.

**Comment by ezekiiel** [comment]
This might also be done by writing a wrapper query contract that does the needed subqueries to give you what you want in terms of info. For example, if we wanted to be able to get the entire config of a DAO in one query we could write a contract to do all those queries and return the results when queried.

**Comment by JakeHartnell** [comment]
Closing as stale.
