### ISSUE TITLE
Disable proposal modules instead of removing them.

### ISSUE THREAD

**Issue by ezekiiel** [DA0-DA0/dao-contracts#377]
Currently to disable a proposal module it is removed from the core contract. This causes trouble in the frontend because it makes assigning globally unique names to proposals hard. Instead of removing modules from the module list we should instead mark them as "disabled". They will still appear in queries, but will not be able to execute messages on the core module.

For example, say we have two proposal modules. They each keep their own proposal counter. We might label proposals by mapping letters to an index and then prepending the mapped index to the proposal id. This would make proposal 1 in the first module proposal "a1" and proposal 1 in the second module proposal "b1".

This works fine, but as soon as a module is removed from the list we're in trouble as our names now change.

Implementing this will require two changes:

1. Make the order modules are returned in queries is a function of when they were added and not a function of their address (right now it is alphabetical).
2. Disable modules instead of removing them from the module list. This will likely involve changing the type of the proposal module list item to something like `{ address, enabled }`.

**Comment by ezekiiel** [comment]
Actually, @NoahSaso has an even better idea. Instead of all of these changes, let's allow specification of a prefix for each module. For example, a module list for Dog Dao might look like:

```
[
  {"woof", "juno..."},
  {"bark", "juno..."}
]
```

Then the first proposal of the woof module would be `daodao.zone/dao/juno.../proposals/woof1`.

**Comment by janitachalam** [comment]
what we decided on: 

1. change PROPOSAL_MODULES in cw-core state to be a list of structs with prefixes and addresses. The prefix will correspond to the uri substring when pointing to a proposal from the module, e.g. daodao.zone/dao/juno.../proposals/a1, where "a" is the prefix
2. When you upgrade a proposal module, keep around the address of the old one in the list, but have a "status" member in the struct to denote "disabled" or "active."
3. For backwards compatibility for the DAOs using the old cw-core contract, wherever we call DumpState in the frontend and there's no prefix for a module, create an object with an empty prefix
