### ISSUE TITLE
Support using native tokens for proposal deposits

### ISSUE THREAD

**Issue by JakeHartnell** [DA0-DA0/dao-contracts#387]
Some DAOs may want to use native tokens like Juno for proposal deposits.

This would work well for more open "anyone can submit" style DAOs like in #386 to help fight spam or as part of the process for raising a treasury.

**Comment by ezekiiel** [comment]
Have done this work for cw-plus here: https://github.com/CosmWasm/cw-plus/pull/751

Feel like it came together reasonably nicely. Should probably reuse this design.

**Comment by mikedotexe** [comment]
Thanks for the link @ezekiiel! I tried reading that PR but will admit it didn't click immediately. Nonetheless, I believe we can take a stab at this. Perhaps I'll follow up with questions in Discord if we get stuck. 🙏🏼

**Comment by ezekiiel** [comment]
Great! Thanks @mikedotexe! Discord is a great place to ask questions. Happy to help.

**Comment by 0xekez** [comment]
https://github.com/DA0-DA0/dao-contracts/pull/481
