### ISSUE TITLE
Pay to propose

### ISSUE THREAD

**Issue by JakeHartnell** [DA0-DA0/dao-contracts#388]
Currently we have two settings for proposal deposits:
- Fully refundable (even if it fails)
- Not refundable if it fails

We should add a third option: _Not refundable. Pay to propose_

This is useful for certain types of DAOs that may have a more open "anyone can propose" aspect.

**Comment by mikedotexe** [comment]
We'd like to take this on, please.

**Comment by JakeHartnell** [comment]
> We'd like to take this on, please.

Go for it! I think this is a good first issue to get started with. Happy to answer any questions.
