### ISSUE TITLE
"Deposit Period" proposal status, allow multiple people to submit deposits

### ISSUE THREAD

**Issue by JakeHartnell** [DA0-DA0/dao-contracts#389]
If proposal deposits are enabled, it would be nice if multiple people could team up to submit a proposal deposit. This mirrors things work in the Cosmos SDK governance module.

Use case: imagine a very large DAO with a very high proposal deposit. Poorer DAO members may not be able to afford the full deposit, but they can create a proposal and convince others to join in.

Adding this period gets us really close to the full proposal life cycle we're aiming for:
```
draft -> deposit -> live -> executed
```

This change will have some UX implementations. For convenience, it would still be nice if I can create a proposal and pay the deposit in the same create proposal transaction.

**Comment by JakeHartnell** [comment]
Think this will need a larger refactor. Really like this approach: https://github.com/DA0-DA0/dao-contracts/discussions/462

**Comment by 0xekez** [comment]
https://github.com/DA0-DA0/dao-contracts/pull/481
