### ISSUE TITLE
cw-multi-voting

### ISSUE THREAD

**Issue by Callum-A** [DA0-DA0/dao-contracts#398]
Opening a ticket with a link to the spec, self assigning as I want to stream this. can give a good overview to people wanting to get into DAO DAO.

Here is the spec:

https://gist.github.com/Callum-A/53319b415246a89cade7e656fc8ff01d

**Comment by JakeHartnell** [comment]
User story: As a DAO, I want to have mixed voting power, allowing both a multisig and governance token holders to vote in a DAO.

A SubDAO may have a core multisig of 5 people with 49% of the voting power in a DAO, while governance token holders could be given 51%. Such a voting power contract would give the "experts" a lot of wait, but ultimately give the community slightly more power. To pass a proposal in this hypothetical DAO, multisig members would have to convince a certain about of the wider community to vote with them.

There are many possible configurations for this feature, really excited for what it will enable.

**Comment by JakeHartnell** [comment]
What are the chances we could get this into v2?

**Comment by JakeHartnell** [comment]
Closing in favor of #803.
