### ISSUE TITLE
Be consistent with "owner manager" or "admin" logic.

### ISSUE THREAD

**Issue by 0xekez** [DA0-DA0/dao-contracts#402]
In our staking contracts we currently have the concept of an "owner" and a "manager". The owner can change the unstaking duration, the owner, and the manager. The manager can change the unstaking duration and the manager, but the owner.

Our other contracts only have the concept of an "admin". The admin and perform all actions, but can not delegate easily.

Should we move all of our contracts to an "owner manager" system? Does it make sense for the staking contracts to be the only one with this pattern? Should we move to an only "admin" system?

**Comment by ezekiiel** [comment]
Some discussion with @janitachalam in the Discord. Way forward seems to be to remove the admin / manager setup.

**Comment by JakeHartnell** [comment]
Believe this is done and that we're now using `cw-ownable` as many places as possible.

**Comment by JakeHartnell** [comment]
Feel free to make issues for contracts where this work needs to be done.
