### ISSUE TITLE
Standardize proposal module contract names.

### ISSUE THREAD

**Issue by NoahSaso** [DA0-DA0/dao-contracts#404]
The current `cw-proposal-single` `CONTRACT_NAME` returned in the info query is `crates.io:cw-govmod-single`, and for `cw-proposal-multiple`, it's `crates.io:cw3-multiple-choice`.

We should standardize these, likely to `crates.io:cw-proposal-single` and `crates.io:cw-proposal-multiple`.

**Comment by JakeHartnell** [comment]
Related to #255.

**Comment by ezekiiel** [comment]
Closing in favor of #416 .
