### ISSUE TITLE
Variable voting thresholds per-actions

### ISSUE THREAD

**Issue by elsehow** [DA0-DA0/dao-contracts#414]
DAO contracts should allow variable voting thresholds for specific actions.

Examples:

- Amending a constitution may require a 75% passing threshold.
- Burning someone's governance tokens may require a 75% passing threshold.

Specifying actions and relating them to passing thresholds is one thing, but this problem is tricky for another reason: we do not have an answer to the question, "how will governance _change_ the passing threshold for a particular ansewr?" Consider: if we made a custom proposal module, governance could always vote to replace that module with a new one that nullifies the origional passing threshold (h/t @NoahSaso for this observation).

**Comment by JakeHartnell** [comment]
This is doable with in a carefully setup DAO with multiple proposal modules and #694.

The DAO main DAO would hold the highest level actions (constitutions, SubDAO admin, upgrades, Authz permissions), while most of the voting would happen through scoped SubDAOs.
