### ISSUE TITLE
Update contract naming scheme.

### ISSUE THREAD

**Issue by 0xekez** [DA0-DA0/dao-contracts#416]
We should migrate to a more consistent contract naming scheme.

Discussed in the discord, let's do `cw-dao-<module_type>-<module_description>`. For example, `cw-proposal-single` would change to `cw-dao-proposal-single` and `cw20-staked-balances-voting` to `cw-dao-voting-cw20-staking`. As part of this work, lets also move all of the proposal and voting modules to their own `proposal-modules` and `voting-modules` subfolders in `contracts/`. We can put READMEs in those subfolders explaining what the modules are and how they work.

Once we do this we will be ready to release these contracts on crates.io.

**Comment by ezekiiel** [comment]
This will need to be the last step before we release v2. Otherwise, the rebase here is going to be insane.

**Comment by 0xekez** [comment]
https://github.com/DA0-DA0/dao-contracts/pull/497
