### ISSUE TITLE
Evaluate and / or implement absolute percentage threshold in multiple choice voting

### ISSUE THREAD

**Issue by blue-note** [DA0-DA0/dao-contracts#430]
https://discord.com/channels/895922260047720449/900071727718088835/1003718082256179271

Originally it was decided to only go with a quorum threshold for votes cast toward _all_ choices, after which either first-past-the-post or ranked-choice voting logic will be applied. Evaluate whether it makes sense to have the analogous absolute percentage threshold as well.

**Comment by JakeHartnell** [comment]
IMO we don't need it. Adds too much complexity and not sure how useful it will be in the context of multiple-choice.

If someone has a really strong use-case for this, feel free to re-open with your rational and use case.
