### ISSUE TITLE
Ability to upgrade the core DAO module

### ISSUE THREAD

**Issue by JakeHartnell** [DA0-DA0/dao-contracts#434]
@ethanfrey has some ideas for how the core DAO contract can be it's own admin, giving it the ability to upgrade itself.

**Comment by janitachalam** [comment]
Curious to hear these ideas! Currently what we've done is [have a factory contract ](https://github.com/DA0-DA0/dao-contracts/tree/main/contracts/cw-admin-factory/src) which instantiates the core contract and then makes it its own admin so that it can upgrade itself.

**Comment by JakeHartnell** [comment]
Wow! You already did it! Genius! Thank you!
