### ISSUE TITLE
Change all "Unauthorized" errors to be more specific

### ISSUE THREAD

**Issue by blue-note** [DA0-DA0/dao-contracts#435]
Generally, generic "unauthorized" errors serve the function of not leaking sensitive or unnecessary info to unauthorized actors in closed-source systems. In this case since we are open-source, having generic unauthorized errors makes less sense: it would be more useful to include more information in the error message to assist in troubleshooting.

**Comment by JakeHartnell** [comment]
Removed the "good first issue" label because while technically very simple, it does require knowledge of the codebase to write better errors for what's happening in each case.

**Comment by JakeHartnell** [comment]
This is a great suggestion, but alas, it's pretty stale. Something we should keep in mind for refactors in the future.
