### ISSUE TITLE
Outdated type codegen dependency

### ISSUE THREAD

**Issue by sascha1337** [DA0-DA0/dao-contracts#436]
https://github.com/DA0-DA0/dao-contracts/blob/cef33570e41c52b04acd692cdd527c836185fd13/types/package.json#L21

This repo moved to cosmwasm organization on github, and is published on NPM now under [@cosmwasm/ts-codegen](https://www.npmjs.com/package/@cosmwasm/ts-codegen)

**Comment by sascha1337** [comment]
This would also need to be adjusted on that line here: 
https://github.com/DA0-DA0/dao-contracts/blob/main/types/src/codegen.ts#L85

But imho, the current implementation is suboptimal here, it works, but im 100% sure that we can get this more safe and clean via programmable usage of his library. Security-wise, definitely always better to **avoid** spawning child processes pointing to _any_ node_modules folder.

Instead of using exec methods, just to pass some args to the cli provided, i'd rather get some programmable functions up, that could straight be import {}'ed and ran inside the script. If currently not possible, i'll make sure that it will.

**Comment by de-husk** [comment]
Great points, Ill fix both of these issues.

Thanks for bringing this up!
