### ISSUE TITLE
PR review discord bot actions

### ISSUE THREAD

**Issue by blue-note** [DA0-DA0/dao-contracts#439]
Not really a contracts issue, but the following ideas were discussed at our last eng meeting: 

1. Have a list of people for reviews out of which 3-4 get randomly selected for each review (either on GitHub or discord) 
2. Automate tagging people on discord who were added to a GitHub review: https://gist.github.com/jagrosh/5b1761213e33fc5b54ec7f6379034a22

**Comment by JakeHartnell** [comment]
Closing as not really a contracts issue. We should think of a good place for these type of issues. Open to suggestions.

**Comment by JakeHartnell** [comment]
Closing as not really a contracts issue. We should think of a good place for these type of issues. Open to suggestions.
