### ISSUE TITLE
Address DAO image URL having length constraint

### ISSUE THREAD

**Issue by mikedotexe** [DA0-DA0/dao-contracts#440]
When providing a URL for a DAO, it's possible to give a value that's so long it runs into gas issues that cannot be fixed by manually attaching more gas with your preferred wallet.

This may be slightly related to this issue and the delicious pasta mentioned in it:
https://github.com/DA0-DA0/dao-contracts/issues/134#issuecomment-1010297060

I did something unusual to see this behavior: instead of adding a web URL I pasted a Data URL as described in this MDN doc:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs

And during the wizard, it worked! At least the preview was showing up nicely:

<img width="1218" alt="Screen Shot 2022-08-08 at 2 26 06 PM" src="https://user-images.githubusercontent.com/1042667/183525352-91231c8f-4132-4c77-b980-f7554608fdbe.png">

But then as I finished the wizard, we got a gas error:

>Query failed with (18): out of gas in location: wasm contract; gasWanted: 300000, gasUsed: 307907: out of gas: invalid request

I tried using Keplr to manually set the gas, giving it 10 million more gas, but got the same error. I'll admit I haven't dug into the contracts yet to determine where exactly this is happening, but I know the DAO DAO contracts make use of hooks and cross-contract calls/messages, and will guess that this OOG (out of gas) is related to it.

Here's a screenshot of the error:

<img width="1550" alt="Screen Shot 2022-08-08 at 2 31 22 PM" src="https://user-images.githubusercontent.com/1042667/183525579-837512b6-8da3-477d-9f02-4a5e1408cd0b.png">

------

I personally think it would be great to be able to use Data URLs so we never have to rely on image links going stale, and the image itself isn't expensive to store on-chain. 

But broadly, outside of using Data URLs, I suppose it's technically possible for a regular URL to get so long that it will run into this same problem.

The ideal solution might be to have the smart contract check the length of the URL and add some (ballpark) extra gas during the cross-contract calls that are probably throwing this error. While you could probably geek out on the perfect computer science way to do this, figuring out the bytes per gas unit, I feel like estimates would be fine, too.

Perhaps there could be a spike or sprint on this broader subject, to help developers inform end users of how much gas they'll need to pay for the storage they're writing. But again, that's possibly dreaming too big. For now, I'd say this ticket is about making sure we either enforce a maximum length so people don't accidentally run into this problem, or implementing a ballpark metric based on the URL length that will correctly add more than enough gas for the DAO creation to succeed.

**Comment by JakeHartnell** [comment]
Closing as stale, feel free to re-open if you feel strongly.

IMO, it's fine to have a length constraint. :joy:
