### ISSUE TITLE
SubQuery // TheGraph search indexer

### ISSUE THREAD

**Issue by sascha1337** [DA0-DA0/dao-contracts#446]
interchain-police not happy with centralized search engine implementation

get rid of this
```

:authority: dao-search.withoutdoing.com
:method: POST
:path: /indexes/v1-mainnet-daos/search
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
authorization: Bearer geDQZEly47de425b96a1ae8ee53917e75fc8ea27b09afb4dbaec202b91e6ac59f341c568

```
replace with SubQuery // TheGraph thx

**Comment by sascha1337** [comment]
https://github.com/subquery/cosmos-subql-starter/commit/ab1559d7cf2cc221fdbd9e1ec023780eaa1b049b

**Comment by sascha1337** [comment]
https://forum.thegraph.com/t/gip-0022-tendermint-indexing-for-graph-node/2815/8
cc zack

**Comment by JakeHartnell** [comment]
Believe @patiee is already working on this.

**Comment by JakeHartnell** [comment]
Being worked on in a separate repo.

**Comment by patiee** [comment]
Hi! You can find here [Juno Indexer ](https://github.com/patiee/juno-indexer)
