### ISSUE TITLE
Allow voting on all proposals up to expiration time.

### ISSUE THREAD

**Issue by 0xekez** [DA0-DA0/dao-contracts#463]
We should allow people to vote on proposals that have already passed, or already been rejected up to their expiration time. This allows better final tallies.

For example, currently with a majority threshold, if 99% of voters support it the final tally will only ever show that 50% voted yes. If we allow voting on passed proposals that 99% of people could still vote and have their position recorded on chain.

Credit to @maurolacy for thinking of this: https://github.com/CosmWasm/cw-plus/pull/784

**Comment by maurolacy** [comment]
You might also want to take a look at https://github.com/CosmWasm/cw-plus/pull/783, in which a bug is fixed in the close proposal handler.

**Comment by NinoLipartiia** [comment]
Hey, I'm starting working on this issue if it is okay for the first ticket
