### ISSUE TITLE
Test proposal logic edge cases

### ISSUE THREAD

**Issue by elsehow** [DA0-DA0/dao-contracts#47]
We should have some tests on contract edge cases. A few that have come up (more ideas welcome):

- A number of people make proposals, and someone makes a proposal that spends their deposits.
- User Alice makes a deposit, a proposal passes that changes the deposit amounts, Alice gets her original deposit back.

These are tests that should *fail* until we address the issue described in #12

**Comment by JakeHartnell** [comment]
Closing as duplicate of #12... tests should be written for that.
