### ISSUE TITLE
Remove timestamps from contracts

### ISSUE THREAD

**Issue by 0xekez** [DA0-DA0/dao-contracts#485]
this has been a journey, but after discussion with @NoahSaso i'd like to suggest that we remove timestamps used only in the frontend from our contracts. in particular, this would mean removing the `last_updated` field from proposals in `cw-proposal-single` and `cw-proposal-multiple`.

as a guiding philosophy: we should keep our on-chain data as simple as possible. it is much easier to fix a bug in an indexer than to fix a bug in our contracts. in the case of timestamps, we can get that data pretty much effortlessly with an indexer and we already [have a couple](https://github.com/DA0-DA0/subquery-indexers) going and doing so.

yay! we get to remove code!

**Comment by JakeHartnell** [comment]
Not sure how I feel about this. Honestly, I think timestamps are essential data... currently, we only use them in the frontend, but I can imagine a scenario where they might be used in another contract.

It's not too much data to store. If we are worried about state we should work to store proposal text on something like IPFS. Yes, we can get this data from indexers but I like not having to rely on indexers to heavily if need be.

**Comment by JakeHartnell** [comment]
This is resolved right?
