### ISSUE TITLE
try a new code coverage tool 

### ISSUE THREAD

**Issue by blue-note** [DA0-DA0/dao-contracts#500]
the current codecov tool in GitHub we use doesn't seem to be super accurate for measuring code coverage -- experiment with other rust code coverage tools

**Comment by JakeHartnell** [comment]
@de-husk any ideas?

**Comment by de-husk** [comment]
So looking at what we have now, we are actually using [cargo tarpaulin](https://github.com/xd009642/tarpaulin) to generate the actual report: 
https://github.com/DA0-DA0/dao-contracts/blob/main/.github/workflows/codecov.yml#L16

So we might as well keep using codecov to view the reports in github.

We should try this code coverage tool to see if it is more accurate for us: https://github.com/mozilla/grcov

**Comment by JakeHartnell** [comment]
Closing until there is a more concrete plan. Feel free to re-open with one.
