### ISSUE TITLE
Figure out how to share testing code across contracts

### ISSUE THREAD

**Issue by 0xekez** [DA0-DA0/dao-contracts#551]
i'd like to be able to write a testing helper method like `make_proposal() -> Result<u64, ContractError>` which i can use in both `cwd_proposal_single` and `cwd_pre_propose_single`.

i'd also like the following to be true:

1. i can use `cw_multi_test` in my `make_proposal` function.
2. `cw_multi_test` does not get compiled for non-production builds.

**Comment by 0xekez** [comment]
## first attempt

import functions directly from the testing package.

for example, i might write:

```rust
#[test]
fn test_attach_to_existing_proposal_module() {
    use cwd_proposal_single as cps;

    let cps::testing::CommonTest {
        mut app,
        core_addr,
        proposal_module,
        gov_token,
        proposal_id,
    } = cps::testing::setup_test(vec![]);
    // ...
}
```

this however fails as the `testing` module is only enabled if `cfg(test)` is true. rust does not set test as true on dependencies, even if it is true for the parent module. thus, name resolution for the `testing` package will fail.

**Comment by 0xekez** [comment]
## second attempt

move functions into `cwd_testing`.

for example, i might create a folder `cwd_testing/src/proposal_single`, then move `execute.rs`, `query.rs`, and `instantiate.rs` there. then, inside `cwd_proposal_single` can rewrite methods to use the ones imported from `cwd_testing`:

```rust
    use cwd_testing::proposal_single::execute::execute_proposal_should_fail;

    let err = execute_proposal_should_fail(&mut app, &proposal_module, CREATOR_ADDR, proposal_id);
    assert!(matches!(err, ContractError::NotPassed {}))
```

sadly, this fails with:

```
error[E0308]: mismatched types
  --> contracts/proposal/cwd-proposal-single/src/testing/adversarial_tests.rs:62:27
   |
62 |     assert!(matches!(err, ContractError::NotPassed {}))
   |                      ---  ^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `cwd_proposal_single::error::ContractError`, found enum `error::ContractError`
   |                      |
   |                      this expression has type `cwd_proposal_single::error::ContractError`
```

as it appears that rust is unable to gleen that these are actually referring to the same enum.

**Comment by Art3miX** [comment]
About the `cwd_testing` option,
Have you tried "exporting" the enums from `cwd_testing` and using those in your tests?

So in  `cwd_testing` do something like:
```rust
pub use cwd_proposal_single::error::ContractError as PropSingleContractError;
```

Then you should be able to use `PropSingleContractError` in your tests and import it from `cwd_testing` rather then the crate directly.

Really long annoying work around, but should get this working.

**Comment by JakeHartnell** [comment]
Feel like we've made progress on this? I'm going to close this because it's large scope without a clear end in sight.

Feel free to open new tickets with more concrete and actionable tasks.
