### ISSUE TITLE
Fix pre-propose-approver singleton bug

### ISSUE THREAD

**Issue by 0xekez** [DA0-DA0/dao-contracts#553]
there's a bug in the contract atm. order of operations:

1. there are two new proposal hook receivers: [them, pre-propose-approver]
2. proposal is approved, deposit is snapshotted into singleton, and proposal is created
3. new proposal hooks fire, first them and then us
4. them dispatches two messages to create a new proposal, and then approves the proposal
5. the approved proposal causes a new deposit to be snapshotted into the singleton, overriding the old one, then it receives the new proposal hook and deletes the singleton's value
6. it is now our turn in the new proposal hook list, we check the singleton and there is no value

this means that being able to approve proposals also gives you the ability to remove your pre-propose module, as:

7. as the singleton has no value, we error
8. proposal module detects error and evicts pre-propose module

this is a privilege escalation.

we're going to merge this into main as it will be very helpful in preventing merge conflicts. we will not ship v2 before closing this issue.

**Comment by JakeHartnell** [comment]
Le done with #554.
