### ISSUE TITLE
Update github actions to use versions that support Node.js16

### ISSUE THREAD

**Issue by de-husk** [DA0-DA0/dao-contracts#572]
Github is going to drop support for actions running <NodeJS 16 by ["Summer 2023"](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/).

You can see the deprecation warnings in the CI job summaries. 

Sadly we need to entirely stop using [`actions-rs/cargo`](https://github.com/actions-rs/cargo/issues) as it [has been confirmed to be no longer maintained](https://github.com/actions-rs/cargo/issues/216#issuecomment-1329850830) will just stop working.

**Comment by de-husk** [comment]
Looks like https://github.com/dtolnay/rust-toolchain is a good alternative.

**Comment by JakeHartnell** [comment]
Don't think this is relevant anymore?

**Comment by dtolnay** [comment]
@JakeHartnell, still relevant. This never got fixed. The current `main` branch (currently https://github.com/DA0-DA0/dao-contracts/commit/9261bb355ca9830cd18536d8576bf1cc20a6848a) still has `actions-rs/cargo` multiple places in its CI. The CI job summaries are still showing piles of alerts about this problem.

https://github.com/DA0-DA0/dao-contracts/blob/9261bb355ca9830cd18536d8576bf1cc20a6848a/.github/workflows/basic.yml#L23-L28
