### ISSUE TITLE
Staking

### ISSUE THREAD

**Issue by JakeHartnell** [DA0-DA0/dao-contracts#58]
After some thought, it's better to stake the Gov tokens in order to participate in governance.

**Comment by ben2x4** [comment]
Here is a new token that implements staking and configurable unstake duration https://github.com/DA0-DA0/cw20-staking

**Comment by JakeHartnell** [comment]
> Here is a new token that implements staking and configurable unstake duration https://github.com/DA0-DA0/cw20-staking

Awesome! So we just need to update `cw20-gov` to use this? Probably need to think about how this impacts UI / UX as well.
