### ISSUE TITLE
Test `dao-voting-native-staked` against token factory

### ISSUE THREAD

**Issue by NoahSaso** [DA0-DA0/dao-contracts#659]
Token factory is coming to Juno mainnet very soon (it's already on testnet!).
Juno PR: https://github.com/CosmosContracts/juno/pull/368
Module: https://github.com/CosmosContracts/token-factory/tree/main/x/tokenfactory

The [`dao-voting-native-staked`](https://github.com/DA0-DA0/dao-contracts/tree/main/contracts/voting/dao-voting-native-staked) voting contract already supports native denoms, and we likely want to switch token-based DAOs to using token factory tokens instead of cw20s... eventually. Before doing all THAT, we should probably test this thoroughly against the new x/tokenfactory module since new code was added and code scary sdk code scary nightmare nightmare big huge danger time oh no. Let's test it!

**Comment by JakeHartnell** [comment]
DONE

**Comment by JakeHartnell** [comment]
Wound up creating a separate contract for Token Factory DAOs.
