### ISSUE TITLE
Allow parent DAO to stop a subDAO proposal from passing if they are in the process on voting to dispute it.

### ISSUE THREAD

**Issue by 0xekez** [DA0-DA0/dao-contracts#662]
Suggested by pupmos (@siriustaikun) [here](https://twitter.com/pupmos/status/1630320704355958784?s=20).

DAOs should have a proposal type that signals that they would like to dispute a subDAO proposal. If such a proposal is created, it should pause the subDAO proposal until the parent DAO can complete deliberation.

The big design question here is:

How do we prevent someone from spamming the parent DAO with proposals of this type and in doing so stopping subDAO execution?

One suggestion might be to only trigger the pause if the proposal in the parent DAO reaches some "quorum" of yes votes. This could be configured on a per-DAO basis.

**Comment by 0xekez** [comment]
another idea might be to draw from Maker DAO's [emergency shutdown module](https://docs.makerdao.com/smart-contract-modules/shutdown). members of the parent DAO could put up stake (with $$ value), if the deliberation was solidly rejected, they would have their stake burned. Otherwise, they would have it returned upon deliberation's completion.

Obviously, much tuning to be done here. Just an idea.

**Comment by JakeHartnell** [comment]
Think #736 and #737 are the answers here.
