### ISSUE TITLE
`dao-voting-native-staked` missing features

### ISSUE THREAD

**Issue by JakeHartnell** [DA0-DA0/dao-contracts#664]
- [ ] Hooks like cw20-stake and NFT staking
- [ ] Support active threshold
- [ ] Create a native token on Instantiation like cw20 or use existing

**Comment by sascha1337** [comment]
Q: from the pure logic / technical side:

would it be possible, to implement dao-voting via NFT staking, of EXISTING stargaze NFTs, using some kind of (... custom pre-ICF wasm based ICA bridge implementation like @0xekez did ) bridge deployed on stargaze and juno ?

**Comment by JakeHartnell** [comment]
> would it be possible, to implement dao-voting via NFT staking, of EXISTING stargaze NFTs, using some kind of (... custom pre-ICF wasm based ICA bridge implementation like @0xekez did ) bridge deployed on stargaze and juno ?

It's possible to support them via ICS721. More thought needs to be given on how voting cross-chain with IBC might work... but could be possible with @0xekez's latest work.

**Comment by JakeHartnell** [comment]
Note, the main challenge here will be testing. Also working on this in the `cw-abc` branch.

**Comment by JakeHartnell** [comment]
DONE
