### ISSUE TITLE
Add info queries to `cw-vesting`

### ISSUE THREAD

**Issue by NoahSaso** [DA0-DA0/dao-contracts#671]
this is my wishlist to improve frontend UX for the vesting contract:

- `vested`: the amount of money that has been unlocked; it may be claimed, staked, unstaking, or any combination of the possible states of the money. i just want the value in the curve that has been vested
- `total`: the total amount of money being vested. amount vested should eventually reach this value
- `duration`: the duration after which `vested` equals `total`, i.e. all money is vested.

making these changes would completely remove the need for the frontend to know what curves are supported, which means we would automatically support vesting contracts in the future with any curve. it also greatly simplifies the math on the frontend, and we all know JS's `Number` math is scary.

i think the first two values should not change even when slashing occurs. i can always subtract slashes from the total when displaying it, but i think it's good to have a distinction between how much the recipient was given vs how much they will actually get.

from those two, i can also calculate the amount that is available to stake with `total - claimed - staked - slashed`.

also, not a big deal, but standardizing all of the durations/timestamps to be in one unit would be nice. second-precision is sufficient.

**Comment by 0xekez** [comment]
thank you for this issue my sir 🙏
