### ISSUE TITLE
Fix packages with incorrect versions

### ISSUE THREAD

**Issue by NoahSaso** [DA0-DA0/dao-contracts#685]
A couple packages did not get their versions updated to `2.1.0`:
- `cw-fund-distributor` (`0.1.0`)
- `cw-payroll-factory` (`2.0.0-beta`)
- `dao-proposal-condorcet` (`0.1.0`)
- `dao-migrator` (`2.0.2`)

**Comment by JakeHartnell** [comment]
Le done.
