### ISSUE TITLE
support subDAO migration

### ISSUE THREAD

**Issue by 0xekez** [DA0-DA0/dao-contracts#687]
instead of executing proposal hook to execute migrate, we execute proposal hook, to execute admin execute on subDAO, to execute migrate.

**Comment by 0xekez** [comment]
specifically, the configuration is:

- parent DAO is contract admin of subDAO.
- subDAO is admin of its own modules.

so, the core migrate for the subSAO needs to be execute by the parent DAO, and the rest of the messages should be executed by the subDAO via the admin execute method.

**Comment by 0xekez** [comment]
cc @Art3miX, does what i outline here make sense? this is required for juno subDAOs to upgrade.

**Comment by JakeHartnell** [comment]
@Art3miX did we ever address this? It's closed right?

**Comment by Art3miX** [comment]
@JakeHartnell i think so, dao-migrator need core to be v2 before it can start, so any dao can upgrade core separately and then execute dao-migrator in a separate proposal.
Or run migrator with the upgrade of the core, so it should cover all cases.
