### ISSUE TITLE
Investigate migration of v0.2.5 to v0.2.6 cw20-stake contracts

### ISSUE THREAD

**Issue by 0xekez** [DA0-DA0/dao-contracts#688]
https://github.com/DA0-DA0/dao-contracts/compare/v0.2.5...v0.3.0

![image](https://user-images.githubusercontent.com/30676292/228631370-077fdeaf-c81c-4f77-9e49-8c26789105c5.png)

Between these two versions, the state changed so that a 0.2.5 staking contract can not safely migrate. We need to write migration logic to allow migration of the `admin` field of the config to `owner` so that we can upgrade DAOs. We can likely do this by extending the existing `migrate` method in that contract.

**Comment by JakeHartnell** [comment]
@Art3miX any updates on this? Know there has been some discussion in the Discord.

**Comment by Art3miX** [comment]
Not sure, i think @NoahSaso got it?
