### ISSUE TITLE
Rename `does_vote_count_pass` parameter

### ISSUE THREAD

**Issue by bekauz** [DA0-DA0/dao-contracts#689]
In `dao-voting` there is a method for evaluating whether quorum is met:
```rust
pub fn does_vote_count_pass(
    yes_votes: Uint128,
    options: Uint128,
    percent: PercentageThreshold,
) -> bool { <...> }
```

While it does what it's supposed to, in `dao-proposal-multiple`, the total of all `vote_weights` is passed as `yes_votes` argument which makes me feel like there could be a better name for the argument.

**Comment by JakeHartnell** [comment]
Done.
