### ISSUE TITLE
Juno v17 will cause some contracts to function unexpectedly

### ISSUE THREAD

**Issue by CLHRAE** [DA0-DA0/dao-contracts#693]
In Juno v15 it's proposed to increase block frequency to double the rate of block production to (roughly) every 3 seconds.

It is my understanding that  the following contracts accumulate reward distribution per block, which means they will accumulate twice as fast as when they were initially configured:
cw20-stake-rewards-distributor
stake-cw20-external-rewards

It's possible there are other contracts which may be affected.

**Comment by JakeHartnell** [comment]
Not sure what to do about this.

**Comment by JakeHartnell** [comment]
Not sure there is much we can do except make people aware.

**Comment by CLHRAE** [comment]
Yeah, agree (and completely forgot about this).   

Might pop up in discord, but would be a matter of reconfiguring the contracts.
