### ISSUE TITLE
Cannot test/build dao-contracts

### ISSUE THREAD

**Issue by spoo-bar** [DA0-DA0/dao-contracts#696]
With some of the DA0-DA0 repositories being closed source now, including `https://github.com/DA0-DA0/cw-storage-plus` and `https://github.com/DA0-DA0/cw-multi-test` , it is not possible to test or build the project. Error below 👇🏻

```sh
error: failed to get `cw-storage-plus` as a dependency of package `dao-core v2.0.3 (/mnt/c/code/dao-contracts/contracts/dao-core)`

Caused by:
  failed to load source for dependency `cw-storage-plus`

Caused by:
  Unable to update https://github.com/DA0-DA0/cw-storage-plus.git#284b3ffb

Caused by:
  failed to clone into: /home/spoobar/.cargo/git/db/cw-storage-plus-d515d4c473075381

Caused by:
  failed to authenticate when downloading repository

  * attempted to find username/password via `credential.helper`, but maybe the found credentials were incorrect

  if the git CLI succeeds then `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
  unexpected http status code: 404; class=Http (34)
error: Recipe `test` failed on line 9 with exit code 101
```

Maybe its better to replace the dependency to the Cosmwasm org contracts which are open source?
and the contracts build successfully with those anyway.

**Comment by 0xekez** [comment]
hi @spoo-bar ! what branch are you running this on? I believe we are using the CosmWasm dependencies now: https://github.com/DA0-DA0/dao-contracts/blob/9261bb355ca9830cd18536d8576bf1cc20a6848a/Cargo.toml#L44-L45

the story here is that we had temporarily forked those dependencies while confio had paused CosmWasm work, but as soon as the hub prop passed to let them work on CosmWasm again we switched back.

**Comment by spoo-bar** [comment]
Oh didn't check main. Oops.
I was on v2.1.0 tag.
