### ISSUE TITLE
Error when deploying DAO on Juno Testnet via website

### ISSUE THREAD

**Issue by comprido96** [DA0-DA0/dao-contracts#725]
Hi, Im having a problem creating a token-based DAO on Juno Testnet... When I try to approve to create transaction, this error message appears: "Invalid string. Length must be a multiple of 4." Any suggestions?

**Comment by JakeHartnell** [comment]
Ask in the Discord! https://discord.gg/sAaGuyW3D2

This is not really a smart contract issue.
