### ISSUE TITLE
Fix Test tube CI

### ISSUE THREAD

**Issue by JakeHartnell** [DA0-DA0/dao-contracts#769]
Failing for some reason. :joy:

**Comment by poroburu** [comment]
`osmosis-test-tube` requires `go` to build. Using `actions/setup-go@v4` works. 

Verified here on the first 2 TT-CI runs: https://github.com/poroburu/dao-contracts/actions/workflows/test_tube.yml

The error is a bit easier to find if compiling test-tube on a local terminal without go. But the error must only be exposed in a sub-shell on the build system. It also shows up in my local nektos `act -W .github/workflows/test_tube.yml ` run.

https://github.com/osmosis-labs/test-tube/blob/1c0b84048c82122af88ba9990618172d912e1a06/packages/osmosis-test-tube/build.rs#L101

```
| error: failed to run custom build command for `osmosis-test-tube v19.0.0`
| 
| Caused by:
|   process didn't exit successfully: `/home/poro/git/dao-contracts/target/debug/build/osmosis-test-tube-b7052da
25b3d7923/build-script-build` (exit status: 101)
|   --- stdout
|   cargo:rerun-if-changed=./libosmosistesttube
|
|   --- stderr
|   thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, messag
e: "No such file or directory" }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/osmosis-test-tube-152da25b3d7923/build-script-build` (exit status: 101)
|   --- stdout
|   cargo:rerun-if-changed=./libosmosistesttube
|
|   --- stderr
|   thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, me
ssage: "No such file or directory" }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/osmosis-test-tu
be-19.0.0/build.rs:109:10
|   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
| warning: build failed, waiting for other jobs to finish...
| error: Recipe `test-tube` failed on line 23 with exit code 101
[Test Tube Tests/Integration tests]   ❌  Failure - Main Run Test Tube Integration Tests
[Test Tube Tests/Integration tests] exitcode '101': failure
```
Also, locally the next dependency to cause the job to fail is a missing clang install. Which explains the linking errors.

**Comment by poroburu** [comment]
Also, regarding build deltas. The locked nightly toolchain is probably adding ~5 minutes to the build. I thought it was frozen on `Updating crates.io index` and found this information about v1.69 => v1.70

https://github.com/rust-lang/cargo/issues/11014#issuecomment-1573624587

I read something about new nightly versions in Discord needing to be addressed. But I thought this was interesting.
